name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  # ❗ 서브모듈 오류 방지

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
